package com.wide.common.model;

import java.util.ArrayList;
import java.util.List;

import com.wide.common.model.base.BaseArea;
import com.wide.common.model.query.QueryArea;
import com.wide.viewmodel.DataTablesModel;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Area extends BaseArea<Area> {
	public static final Area dao = new Area();
	
	public Page<Area> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from sys_area order by id asc");
	}
	
	/**
	 * datatables 查询
	 * @param @param pageNum
	 * @param @param iDisplayLength
	 * @param @param select
	 * @param @param sqlExceptSelect
	 * @param @param search    设定文件
	 * @return void    返回类型
	 * @throws
	 */
	@SuppressWarnings("rawtypes")
	public DataTablesModel pageDataTables(int pageNum, int pageSize, QueryArea queryArea) {
	    @SuppressWarnings("unused")
		final List<Object> parameters = new ArrayList<Object>();
	    String select = "select id,name,code,type ";
	    StringBuilder sqlExceptSelect = new StringBuilder(" from sys_area  ");
	    /**
	    if (search!=null&&!search.equals("")) {
	        sqlExceptSelect.append(" AND (b.title like ? or b.content like ? )");
	        parameters.add("%" + search + "%");
	        parameters.add("%" + search + "%");
	    } 
	     **/
	    sqlExceptSelect.append(whereQuery(queryArea));
	    sqlExceptSelect.append(orderbyQuery(queryArea));
	    
	    return this.paginateDataTables(pageNum, pageSize, select, sqlExceptSelect.toString());
	}
	
	/**
	 * query where查询
	 * 
	 * */
	private String whereQuery(QueryArea query){
		String where=" where 1=1  and del_flag = 0 ";
		if(query.getAreaname()!=null&&!query.getAreaname().equals("")){
			where += " and name like '%"+query.getAreaname()+"%'";
		}
		if(query.getAreatype()!=0){
			where  +=" and type = "+query.getAreatype();
		}
		if(query.getStarttime()!=null&&!query.getStarttime().equals("")){
			where  +=" and create_date >= '"+query.getStarttime()+"'";
		}
		if(query.getEndtime()!=null&&!query.getEndtime().equals("")){
			where  +=" and create_date <=  '"+query.getEndtime().replace("00:00:00", "23:59:59")+"'";
		}
		return where;
		
	}
	/**
	 * query order by 
	 * 
	 * */
	private String orderbyQuery(QueryArea query){
		String orderby = " order by create_date desc ";
		return orderby;
		
	}
	
	
	
	public List<Area> getAreaAll()
	{
		List<Area> list = find("select * from sys_area where del_flag = 0 order by sort asc");
		return list;
	}
	
	public List<Area> findByPid(String id)
	{
		List<Area> list = new ArrayList<Area>();
		list = find("select * from sys_area where del_flag = 0 and parent_id = '"+id+"'");
		return list;
	}

	public List<Area> getAreasByQuery(QueryArea queryArea)
	{
		// TODO Auto-generated method stub
		String where = whereQuery(queryArea);
		String orderby = " order by sort asc "; 
		List<Area> list = find("select * from sys_area"+where+orderby);
		return list;
	}
}
