package com.wide.common.model;

import com.wide.common.model.base.BaseBespeakexamExaminee;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BespeakexamExaminee extends BaseBespeakexamExaminee<BespeakexamExaminee> {
	public static final BespeakexamExaminee dao = new BespeakexamExaminee();
}
