package com.wide.common.model;

import com.wide.common.model.base.BaseCases;
import com.wide.common.model.query.QueryCase;
import com.wide.common.model.query.QuerySubject;
import com.wide.viewmodel.DataTablesModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cases extends BaseCases<Cases> {
	public static final Cases dao = new Cases();
	
	@SuppressWarnings("rawtypes")
	public DataTablesModel pageDataTables(int pageNum, int pageSize, QueryCase queryCase) {
		// TODO Auto-generated method stub
	    String select = "select id,name,casetitle,caseanswer,isenable";
	    StringBuilder sqlExceptSelect = new StringBuilder(" from sys_cases ");
	    /**
	    if (search!=null&&!search.equals("")) {
	        sqlExceptSelect.append(" AND (b.title like ? or b.content like ? )");
	        parameters.add("%" + search + "%");
	        parameters.add("%" + search + "%");
	    } 
	     **/
	    sqlExceptSelect.append(whereQuery(queryCase));
	    sqlExceptSelect.append(orderbyQuery(queryCase));
	    
	    return this.paginateDataTables(pageNum, pageSize, select, sqlExceptSelect.toString());
	}
	/**
	 * query where查询
	 * 
	 * */
	private String whereQuery(QueryCase query){
		String where=" where 1=1  and isdel = 0 ";
		if(query.getName()!=null&&!query.getName().equals("")){
			where += " and name like '%"+query.getName()+"%'";
		}
		if(query.getCasetitle()!=null&&!query.getCasetitle().equals("")){
			where  +=" and casetitle like '%"+query.getCasetitle()+"%'";
		}
		
		return where;
		
	}
	/**
	 * query order by 
	 * 
	 * */
	private String orderbyQuery(QueryCase query){
		String orderby = " order by create_date desc ";
		return orderby;
		
	}
}
