package com.wide.common.model;

import com.wide.common.model.base.BaseExerciseQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExerciseQuestion extends BaseExerciseQuestion<ExerciseQuestion> {
	public static final ExerciseQuestion dao = new ExerciseQuestion();
}
