package com.wide.common.model;

import com.wide.common.model.base.BaseFolder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Folder extends BaseFolder<Folder> {
	public static final Folder dao = new Folder();
}
