package com.wide.common.model;

import java.util.List;

import com.wide.common.model.base.BaseItembank;
import com.wide.common.model.query.QueryCase;
import com.wide.common.model.query.QueryItemBank;
import com.wide.viewmodel.DataTablesModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Itembank extends BaseItembank<Itembank> {
	public static final Itembank dao = new Itembank();

	
	/**
	 * 通过id查询名称
	 * @return
	 */
	public Itembank getItemBankNameById(String id){
		Itembank list =findById(id);
		return list;
	}

	@SuppressWarnings("rawtypes")
	public DataTablesModel pageDataTables(int pageNum, int pageSize, QueryItemBank queryitembank) {
		// TODO Auto-generated method stub
	    String select = "select id,name,subject_id,sumtotal,questiontype,checknum,isenable ";
	    StringBuilder sqlExceptSelect = new StringBuilder(" from sys_itembank ");
	    /**
	    if (search!=null&&!search.equals("")) {
	        sqlExceptSelect.append(" AND (b.title like ? or b.content like ? )");
	        parameters.add("%" + search + "%");
	        parameters.add("%" + search + "%");
	    } 
	     **/
	    sqlExceptSelect.append(whereQuery(queryitembank));
	    sqlExceptSelect.append(orderbyQuery(queryitembank));
	    
	    return this.paginateDataTables(pageNum, pageSize, select, sqlExceptSelect.toString());
	}
	/**
	 * query where查询
	 * 
	 * */
	private String whereQuery(QueryItemBank queryitembank){
		String where=" where 1=1  and isdel = 0 ";
		if(queryitembank.getName()!=null&&!queryitembank.getName().equals("")){
			where += " and name like '%"+queryitembank.getName()+"%'";
		}
		if(queryitembank.getSubjectid()!=null&&!queryitembank.getSubjectid().equals("")){
			where += " and subject_id like '%"+queryitembank.getSubjectid()+"%'";
		}
		if(queryitembank.getQuestionType()!=null&&queryitembank.getQuestionType()!=0){
			where  +=" and questiontype = '"+queryitembank.getQuestionType()+"'";
		}
		
		return where;
		
	}
	/**
	 * query order by 
	 * 
	 * */
	private String orderbyQuery(QueryItemBank queryitembank){
		String orderby = " order by create_date desc ";
		return orderby;
		
	}

	
}
