package com.wide.common.model;

import java.util.ArrayList;
import java.util.List;

import com.wide.common.model.base.BaseLog;
import com.wide.common.model.query.QueryLog;
import com.wide.util.DateUtil;
import com.wide.viewmodel.DataTablesModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Log extends BaseLog<Log> {
	public static final Log dao = new Log();

	/**
	 * @author phm 获取全部日志
	 */
	public List<Log> getAllLog() {
		List<Log> listlog = find("select * from sys_log");
		return listlog;
	}

	/**
	 * datatables 查询 @param @param pageNum @param @param
	 * iDisplayLength @param @param select @param @param
	 * sqlExceptSelect @param @param search 设定文件 @return void 返回类型 @throws
	 */
	public DataTablesModel pageDataTables(int pageNum, int pageSize, QueryLog queryLog) {
		final List<Object> parameters = new ArrayList<Object>();
		String select = "select id,type,title,content,operatorname,create_date";
		StringBuilder sqlExceptSelect = new StringBuilder("from sys_log");
		sqlExceptSelect.append(whereQuery(queryLog));
		sqlExceptSelect.append(orderbyQuery(queryLog));
		return this.paginateDataTables(pageNum, pageSize, select.toString(), sqlExceptSelect.toString());
	}

	/**
	 *  @author phm query where查询
	 * 
	 */
	private String whereQuery(QueryLog queryLog) {
		String where = " where 1=1";
		if (queryLog.getLogName() != null && !queryLog.getLogName().equals("")) {
			where += " and title like '%" + queryLog.getLogName().trim() + "%'";
		}
		if (queryLog.getStarttimes() != null && !queryLog.getStarttimes().equals("")) {
			where += " and create_date >= '" +queryLog.getStarttimes()+ " 00:00:00'";
		}
		if (queryLog.getEndtimes() != null && !queryLog.getEndtimes().equals("")) {
			where += " and create_date <=  '" +queryLog.getEndtimes()+ " 23:59:59'";
		}
		return where;

	}
	/**
	 * @author phm query order by
	 */
	private String orderbyQuery(QueryLog QueryLog) {
		String orderby = " order by create_date desc ";
		return orderby;
	}
	//
	/**
	 * @author phm 把记录保存到日志
	 */
	public List<Log> saveRecordLog(Log log,User user){
		List<Log> list = find("insert into sys_log (content,create_by,operatorname,create_date)values()"+log.getContent()+log.getCreateDate()+user.getName());
		return list;
	}
}
