package com.wide.common.model;

import java.util.ArrayList;
import java.util.List;

import com.wide.common.model.base.BaseMenu;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Menu extends BaseMenu<Menu> {
	public static final Menu dao = new Menu();
	
	public List<Menu> getMenuAll(){
		List<Menu> list= find("select * from sys_menu where del_flag = 0 order by sort asc");
		return list;
		
	}

	public List<Menu> findByPid(String id) {
		// TODO Auto-generated method stub
		List<Menu> list = new ArrayList<Menu>();
		list= find("select * from sys_menu where del_flag = 0 and parent_id = '"+id+"'");
		return list;
	}

	public List<Object[]> findByMenuPid(String id) {
		// TODO Auto-generated method stub
		List<Object[]> list = new ArrayList<Object[]>();
		list= Db.query("select t1.id,t1.parent_id,t1.name,t2.id from sys_menu t1,sys_right t2 where t1.del_flag = 0 and t1.id = t2.resourcesid and t2.resourcestype = 1 "
				+ "and t1.parent_id = '"+id+"'");
		return list;
	}
	
}
