package com.wide.common.model;

import java.util.ArrayList;
import java.util.List;

import com.wide.common.model.base.BaseOffice;
import com.wide.common.model.query.QueryStatistics;
import com.wide.viewmodel.DataTablesModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Office extends BaseOffice<Office> {
	public static final Office dao = new Office();

	public List<Office> getOfficeByuserID(String userid) {
		// TODO Auto-generated method stub
		List<Office> lists = find(" select t1.* from sys_office t1,sys_office_user t2 where t1.id = t2.office_id and t1.del_flag = 0 and t2.user_id = ? ", userid);
		return lists;
	}

	public List<Office> findByPid(String pid) {
		// TODO Auto-generated method stub
		List<Office> lists = find(" select t1.* from sys_office t1 where 1=1 and t1.del_flag = 0 and t1.parent_id = ? ", pid);
		return lists;
	}
	
	public List<Office> findByRoleId(String id){
		List<Office> lists = find(" select t1.* from sys_office t1,sys_role_office t2 where 1=1 and t1.del_flag = 0 and t1.id = t2.office_id and t2.role_id = ? ", id);
		return lists;
	}

	public List<Office> getOfficeAll() {
		// TODO Auto-generated method stub
		List<Office> list = find(" select t1.* from sys_office t1 where 1=1 and t1.del_flag = 0 order by t1.sort asc");
		return list;
	}
	public List<Office> findOfficeById(String id) {
		// TODO Auto-generated method stub
		List<Office> list = find(" select t1.* from sys_office t1 where 1=1 and t1.del_flag = 0 and t1.id = ? order by t1.sort asc", id);
		return list;
	}
	
	public Office getOfficeById(String id) {
		// TODO Auto-generated method stub
		Office office = findFirst(" select t1.* from sys_office t1 where 1=1 and t1.del_flag = 0 and t1.id = ? ", id);
		return office;
	}

	public DataTablesModel getPageExamCountDapartmentfind(int pageNum, int pageSize, QueryStatistics queryStatistics) {
		// TODO Auto-generated method stub
		final List<Object> parameters = new ArrayList<Object>();
		String select = "select id , name ";
		StringBuilder sqlExceptSelect = new StringBuilder("from sys_office where del_flag = 0 and type = 2 order by create_date desc ");
		return this.paginateDataTables(pageNum, pageSize, select.toString(), sqlExceptSelect.toString());
	}
	
	public DataTablesModel getPageExamCountPostfind(int pageNum, int pageSize, QueryStatistics queryStatistics) {
		// TODO Auto-generated method stub
		final List<Object> parameters = new ArrayList<Object>();
		String select = "select id , name ";
		StringBuilder sqlExceptSelect = new StringBuilder("from sys_office where del_flag = 0 and type = 3 order by create_date desc ");
		return this.paginateDataTables(pageNum, pageSize, select.toString(), sqlExceptSelect.toString());
	}
}
