package com.wide.common.model;

import com.wide.common.model.base.BaseOfficeUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OfficeUser extends BaseOfficeUser<OfficeUser> {
	public static final OfficeUser dao = new OfficeUser();
}
