package com.wide.common.model;

import java.util.ArrayList;
import java.util.List;

import com.wide.common.model.base.BaseRight;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Right extends BaseRight<Right> {
	public static final Right dao = new Right();
	/**
	 * 按角色id查询权限列表
	 * @param id
	 * @return
	 */
	public List<Right> getRoleRightByroleId(String id) {
		// TODO Auto-generated method stub
		List<Right> list = new ArrayList<Right>();
		list = find("select t1.* from sys_right t1,sys_role_right t2 where t1.id=t2.right_id and t1.resourcestype = 1 and t2.role_id = ? order by t1.update_date desc ", id);
		return list;
	}
	/**
	 * 按菜单id查询权限
	 * @param id
	 * @return
	 */
	public Right getRightBymenuId(String id) {
		// TODO Auto-generated method stub
		List<Right> list = new ArrayList<Right>();
		Right right = new Right();
		list = find("select t1.* from sys_right t1,sys_menu t2 where t2.id=t1.resourcesid and t1.resourcestype = 1 and t2.id = ? order by t1.update_date desc ", id);		
		if(list.size()>0){
			right=list.get(0);
		}
		return right;
	}
}
