package com.wide.common.model;

import com.wide.common.model.base.BaseRoleOffice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleOffice extends BaseRoleOffice<RoleOffice> {
	public static final RoleOffice dao = new RoleOffice();
}
