package com.wide.common.model;

import java.util.List;

import com.wide.common.model.base.BaseRoleRight;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleRight extends BaseRoleRight<RoleRight> {
	public static final RoleRight dao = new RoleRight();
	/**
	 * 按id查询角色权限列表
	 * @param id
	 * @return
	 */
	public List<RoleRight> findByRoleId(String id){
		List<RoleRight> lists = find(" select * from sys_role_right t1 where  role_id = ? ", id);
		return lists;
	}

}
