package com.wide.common.model;

import com.wide.common.model.base.BaseTextbook;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Textbook extends BaseTextbook<Textbook> {
	public static final Textbook dao = new Textbook();
}
