package com.wide.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseExampapersQuestion<M extends BaseExampapersQuestion<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setExampapersId(java.lang.String exampapersId) {
		set("exampapers_id", exampapersId);
	}

	public java.lang.String getExampapersId() {
		return get("exampapers_id");
	}

	public void setQuestionId(java.lang.String questionId) {
		set("question_id", questionId);
	}

	public java.lang.String getQuestionId() {
		return get("question_id");
	}

	public void setScores(java.lang.Double scores) {
		set("scores", scores);
	}

	public java.lang.Double getScores() {
		return get("scores");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

	public java.lang.Integer getSort() {
		return get("sort");
	}

}
