package com.wide.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoleOffice<M extends BaseRoleOffice<M>> extends Model<M> implements IBean {

	public void setRoleId(java.lang.String roleId) {
		set("role_id", roleId);
	}

	public java.lang.String getRoleId() {
		return get("role_id");
	}

	public void setOfficeId(java.lang.String officeId) {
		set("office_id", officeId);
	}

	public java.lang.String getOfficeId() {
		return get("office_id");
	}

}
