package com.wide.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseExerciseQuestion<M extends BaseExerciseQuestion<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setExerciseId(java.lang.String exerciseId) {
		set("exercise_id", exerciseId);
	}

	public java.lang.String getExerciseId() {
		return get("exercise_id");
	}

	public void setQuestionId(java.lang.String questionId) {
		set("question_id", questionId);
	}

	public java.lang.String getQuestionId() {
		return get("question_id");
	}

}
