package com.wide.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.wide.config.DbModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRole<M extends BaseRole<M>> extends DbModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setOfficeId(java.lang.String officeId) {
		set("office_id", officeId);
	}

	public java.lang.String getOfficeId() {
		return get("office_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setEnname(java.lang.String enname) {
		set("enname", enname);
	}

	public java.lang.String getEnname() {
		return get("enname");
	}

	public void setRoleType(java.lang.String roleType) {
		set("role_type", roleType);
	}

	public java.lang.String getRoleType() {
		return get("role_type");
	}

	public void setDataScope(java.lang.String dataScope) {
		set("data_scope", dataScope);
	}

	public java.lang.String getDataScope() {
		return get("data_scope");
	}

	public void setIsSys(java.lang.String isSys) {
		set("is_sys", isSys);
	}

	public java.lang.String getIsSys() {
		return get("is_sys");
	}

	public void setUseable(java.lang.String useable) {
		set("useable", useable);
	}

	public java.lang.String getUseable() {
		return get("useable");
	}

	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}

	public java.lang.String getUpdateBy() {
		return get("update_by");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public void setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
	}

	public java.lang.String getDelFlag() {
		return get("del_flag");
	}

}
