package com.wide.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBespeakexamExaminee<M extends BaseBespeakexamExaminee<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setExamId(java.lang.String examId) {
		set("exam_id", examId);
	}

	public java.lang.String getExamId() {
		return get("exam_id");
	}

	public void setExamineeId(java.lang.String examineeId) {
		set("examinee_id", examineeId);
	}

	public java.lang.String getExamineeId() {
		return get("examinee_id");
	}

}
